server:
  port: 80

spring:
  datasource:                                         # Data source related configuration
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: ****
