server:
  port: 8088

spring:
  datasource:                                         # Data source related configuration
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: your pwd
  redis:
    database: 1
    host: your IP
    port: 6379
    password: ***

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#file:
#  imageUserFaceLocation: C:\\Users\\yaowi\\Desktop\\java\\images\\foodie\\faces
#  imageServerUrl: http:\\\\localhost:8088\\foodie\\faces

file:
  imageUserFaceLocation: "C:\\Users\\yaowi\\Desktop\\java\\images\\foodie\\faces"
  imageServerUrl: "http://localhost:8088/foodie/faces"