server:
  port: 80

spring:
  datasource:                                         # Data source related configuration
    url: jdbc:mysql://192.168.74.128:3306/foodie-shop-dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: YOUR_PW
  redis:
    database: 1
    host: 192.168.74.134
    port: 6379
    password: YOUR_PW

file:
  imageUserFaceLocation: /workspaces/images/foodie/faces
  imageServerUrl: http://192.168.74.128:8088/foodie-api/foodie/faces